import * as React from 'react';
import Modal from '@mui/material/Modal';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button'
import Head from 'next/head'

const style = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    border: '2px solid #000',
    boxShadow: 24,
    p: 4,
  };
  

export default function BookModal({data}) {
    const [open, setOpen] = React.useState(false);
    const handleClose = () => setOpen(false);
    const handleOpen = () => setOpen(true);

    return (
        <>
        <Head>
        <title>CBCP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        </Head>

        <Button variant="outlined" color="secondary" onClick={handleOpen}>
        info
        </Button>

                <Modal
                  open={open}
                  onClose={handleClose}
                  aria-labelledby="modal-modal-title"
                  aria-describedby="modal-modal-description"
                >
                  <Box sx={style}
                  className="bg-black"
                  >
                <button className='absolute right-0 top-0 pr-5 pt-2' onClick={handleClose}><i className="fa fa-window-close" style={{fontSize: '25px', color: "white"}}></i></button>
                  <ul className='text-xl text-logo'>
                      <li className='py-2'>Name: {data.name}</li>
                      <li className='py-2'>Medium: {data.med}</li>
                      <li className='py-2'>Size: {data.size}</li>
                      <li className='py-2'>Edition: {data.ed}</li>
                  </ul>
                  </Box>
                </Modal>
                </>
    )
}