import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { mainData }  from '../components/main-data';
import Layout from '../components/Layouts'

export async function getStaticProps() {

  const mainPhotos = mainData;

  return {
    props: {
      mainPhotos
    }
  }
}


export default function Home({mainPhotos}) {

//console.log(mainPhotos);

  return (
    <>

      <Head>
        <title>CBCP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout></Layout>
      <main className='flex flex-col justify-center items-center'>
      <div className="p-10 masonry sm:masonry-sm md:masonry-md lg:masonry-lg">
      {mainPhotos.map(mainPhoto => (
            <div className='hover:opacity-50 p-3 break-inside' key={mainPhoto.id}>
              <Link href={"/"}>
              <img
              src={mainPhoto.url} 
              alt="image"
              ></img>
              </Link>




{/*               <Link href={"/"}>
              <Image src={mainPhoto.url} alt="image" width={200} height={200}></Image>
              </Link>
              <ul>
                <li>Name: {mainPhoto.name}</li>
                <li>Medium: {mainPhoto.med}</li>
                <li>Size: {mainPhoto.size}</li>
                <li>Edition: {mainPhoto.ed}</li>
              </ul> */}
            </div>
          ))}

      </div>
      </main>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/images/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
