import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { mainData }  from '../components/main-data';
import Navigator from '../components/navigator';
//import Layout from '../components/layouts';

export async function getStaticProps() {

  const mainPhotos = mainData;

  return {
    props: {
      mainPhotos
    }
  }
}


export default function Home({mainPhotos}) {

//console.log(mainPhotos);

  return (
    <>
 
      <Head>
        <title>CBCP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigator></Navigator>
      <div className="grid justify-center px-3 py-10 font-Nanum">
        <h1 className="uppercase font-bold leading-snug text-black"
        style={{
          fontSize: '50px'
        }}
        >Screen Prints</h1>

      </div>
      <main className='flex flex-col justify-center items-center bg-black font-Nanum'>
      <div className="p-10 masonry sm:masonry-sm md:masonry-md lg:masonry-lg">
        {mainPhotos.map(mainPhoto => (
              <div className='hover:opacity-50 p-3 break-inside drop-shadow-xl' key={mainPhoto.id}>
                <a href={"/"}>
                <img // eslint-disable-line
                src={mainPhoto.url} 
                alt="image"
                />
                </a>

              {/*<Link href={"/"}>
                <Image src={mainPhoto.url} alt="image" width={200} height={200}></Image>
                </Link>
                <ul>
                  <li>Name: {mainPhoto.name}</li>
                  <li>Medium: {mainPhoto.med}</li>
                  <li>Size: {mainPhoto.size}</li>
                  <li>Edition: {mainPhoto.ed}</li>
                </ul> */}
              </div>
            ))}

      </div>
      </main>
      <footer>
        <a

        >
          Powered by{' '}
          <span>
            <Image src="/images/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
