import booksData from "../../books-data"
import Head from "next/head"
import Link from 'next/link'
import Image from 'next/image'
import Navigator from '../../components/navigator'
import matter from 'gray-matter'
import BookModal from '../../components/bookModal'
import { Carousel } from 'react-responsive-carousel';
import "react-responsive-carousel/lib/styles/carousel.min.css";



export async function getStaticProps() {
  const bookDatas = await booksData.map((books) => {
    const data = books
    return data
  });

  const data = bookDatas

  return {
    props: {
        data
    }
  }
}


export default function Drawings(data) {

  const dataArray = data.data

  return (
    <>
      <Head>
        <title>CBCP Artist Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid justify-center px-3 py-10 font-Nanum">
        <h1 className="uppercase font-bold leading-snug text-black"
        style={{
          fontSize: '40px'
        }}
        >Artist Books</h1>

      </div>
      <main className='flex flex-col justify-center items-center font-Nanum px-24'>
      <div className="p-10 masonry sm:masonry-sm md:masonry-md lg:masonry-lg">
      {dataArray.map(data => (
            <div className='p-3 break-inside w-80 sm:w-96' key={data.id}>
                <Carousel>
                {data.image.map(image => (
                <>
                <img //eslint-disable-line
                src={image}
                alt={data.name}
                />
                </>
                ))}
                </Carousel>
              <BookModal data={data}/>
            </div>
            
          ))}
      </div>


      </main>
      <footer>
        <a>
          Powered by{' '}
          <span>
            <Image src="/images/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      
    </>
  )
}
